######################## default configuration ####################
baseURL = "https://examplesite.org"
languageCode = "en-us"
title = "Vixcon Hugo| Event &amp; Conference hugo template"
theme = "vixcon-hugo"
summaryLength = "10"
paginate = 4

[outputs]
  home = ["HTML", "AMP", "RSS", "JSON"]

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/css/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/themefisher-font/style.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jquery/jquery.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/js/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/SyoTimer/jquery.syotimer.min.js"
  [[params.plugins.js]]
  URL = "http://cdnjs.cloudflare.com/ajax/libs/jquery.form/3.32/jquery.form.js"
  [[params.plugins.js]]
  URL = "http://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.11.1/jquery.validate.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"
  [[params.plugins.js]]
  URL = "plugins/google-map/map.js"

############################## navigation ###############################
[menu]
    
  [[menu.main]]
  name = "About"
  URL = "about"
  weight = 2
  
  [[menu.main]]
  name = "Speakers"
  URL = "speaker"
  weight = 3

  [[menu.main]]
  weight = 4
  name = "Pages"
  hasChildren = true

    [[menu.main]]
    parent = "Pages"
    name = "Tickets"
    URL = "pricing"

    [[menu.main]]
    parent = "Pages"
    name = "Blog"
    URL = "blog"

    [[menu.main]]
    parent = "Pages"
    name = "Schedule"
    URL = "schedule"

    [[menu.main]]
    parent = "Pages"
    name = "FAQ"
    URL = "faq"
    
  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 5

#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Home"
# Meta data
description = "This is meta description"
author = "Themefisher"
# google map
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
mapLatitude = "51.5223477"
mapLongitude = "-0.1622023"
mapMarker = "images/marker.png"
# Google Analitycs
googleAnalitycsID = "Your ID"

  # Preloader
  [params.preloader]
  enable = true

  # Navigation get start button
  [params.navBtn]
  enable = true
  label = "Get Ticket"
  link = "pricing"

  ############################## footer ################################
  [params.footer]
  title = "Vixcon."
  content = "We are a creative-led experiential Event Production Agency that helps brands connect, engage and evolve."
  copyright = "Copyright Reserved to Themefisher.2019"

  ############################# social icon ############################
  [[params.social]]
  icon = "tf-ion-social-facebook"
  link = "#"
  
  [[params.social]]
  icon = "tf-ion-social-twitter"
  link = "#"
  
  [[params.social]]
  icon = "tf-ion-social-linkedin"
  link = "#"
  
  [[params.social]]
  icon = "tf-ion-social-pinterest"
  link = "#"
  
  [[params.social]]
  icon = "tf-ion-social-rss"
  link = "#"